services:
  app:
    build: .
    ports:
      - 3000:3000
    command: ["npx", "next"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: "*.js"
        - action: rebuild
          path: "*.ts"
        - action: rebuild
          path: "*.jsx"
        - action: rebuild
          path: "*.tsx"